### ISSUE TITLE
"Show all categories" in menu item settings does not show categories

### ISSUE THREAD

**Issue by Joomlalife** [joomlaworks/k2-v3-dev-build#120]
Issue: 
Setting up a menu item for a k2_category setting it to show "all" does not make any category appear on the site. 

I had to go back to the menu item and choose the test category I set up. I did not activate the option "select".

It is not a big issue, but it is confusing since I choose "all" as default. Knowing customers I think they will just call back and say "it does not work".

Thanks

**Comment by paulvanharen** [comment]
@kavadas 
When selecting multiple categories, or selecting "all", the categories themselves are not shown anymore. This is different then when displaying one single category. However, this is expected behavior. Therefore I propose to close this issue.
