### ISSUE TITLE
Menu link for "K2 Users will fetch a list of K2 users based on some criteria...."

### ISSUE THREAD

**Issue by Mr-Anonymous** [joomlaworks/k2-v3-dev-build#160]
Whats this new Long Menu link I see in frontend now? Does it need to be shortened?
```
K2 Users will fetch a list of K2 users based on some criteria. You can additionally select to retrieve one or more items for each K2 user.		    					
```
![k2-users-front-end](https://cloud.githubusercontent.com/assets/8770270/5488253/1f254442-86e1-11e4-9740-1f56e5d567c9.png)

**Comment by paulvanharen** [comment]
@kavadas 
This menu item is now showing just "Users", which is correct. Therefore I propose closing this issue.
