### ISSUE TITLE
Menu Item's Default Recursive Setting

### ISSUE THREAD

**Issue by Mr-Anonymous** [joomlaworks/k2-v3-dev-build#170]
When creating the K2 Categories Menu Item, can you set a default option for 'Recursive'? If a user forgets to choose this, they receive an error in frontpage. This is just a minor thing and not a big deal I guess.
![recursive](https://cloud.githubusercontent.com/assets/8770270/5506866/2f209048-87c4-11e4-9881-89fdac816838.png)

**Comment by kbrookes** [comment]
I can confirm this. When I use mod_k2_content to display items from selected categories and do **not** choose a recursive option, I get the following error:

'''
Notice: Undefined property: stdClass::$recursive in /home/mobome/public_html/administrator/components/com_k2/models/items.php on line 183
'''

Choosing a recursive setting resolves the error.

**Comment by kavadas** [comment]
Thank you both for your feedback.
