### ISSUE TITLE
Warning "Invalid segment" on all basics Item pages

### ISSUE THREAD

**Issue by visual74** [joomlaworks/k2-v3-dev-build#183]
Hi,
I've got this warning error on all views item.php in my template:
![K2 Beta warning error](https://s3.amazonaws.com/fvd-data/notes/336662/1421312923-nGgMl3/screen.png)
If you need more informations, just ask to me. Thank you very much.
ViSuaL.

**Comment by kavadas** [comment]
Hi,

Is this an upgrade from K2v2 or a fresh install?

**Comment by visual74** [comment]
K2 v3 / Joomla 3.3.6 fresh install.
I upgraded yesterday (rev 1511). And it's possible I had this before.
Thx.

**Comment by kavadas** [comment]
Can you please check the database table #__k2_items and see what are the contents in the "galleries" field?

**Comment by visual74** [comment]
I've got the (string): 
```
null
```
And I haven't got the error when a gallery is filled.

**Comment by visual74** [comment]
Ho s***, ok my fault, we made a scripted data import, couple months ago, and it put (string)null in the galleries field. And it sould be an empty field.
You can close it...
Sorry for your lost time !

**Comment by kavadas** [comment]
It's fine.
