### ISSUE TITLE
Image upload from "Browse server" broken

### ISSUE THREAD

**Issue by visual74** [joomlaworks/k2-v3-dev-build#184]
Hi,
On Item edit page, when I try to "Upload image", it works well, but from "Browse server.." not.
I chose my image, double-click on, and Save = No change.

In database, after saved, image field = `{"caption":"","credits":"","flag":0}`

![Image upload from "Browse server" broken](https://s3.amazonaws.com/fvd-data/notes/336662/1421769142-3xZ4rx/screen.png)

Thank you.
ViSuaL.

**Comment by kavadas** [comment]
Hi, 

Do you get the thumbnail preview? You need for the thumbnail to get generated and after that save the item. We need to add a loading indicator there probably.

**Comment by visual74** [comment]
No thumbnail, and just after selecting the image, I get this error :
![](https://s3.amazonaws.com/fvd-data/notes/336662/1421824212-IAKnld/screen.png)

**Comment by kavadas** [comment]
This sounds to me like a specific image problem. Can you try with a different image file? What's the file type of the image you are selecting ?

**Comment by visual74** [comment]
I tryed with Jpg and Png, differents sizes, differents compressions. All times the same error message.
My console :
![](https://s3.amazonaws.com/fvd-data/notes/336662/1421837372-g9Sick/screen.png)

**Comment by kavadas** [comment]
Make sure that the files you select have proper permissions . I made some tests and the "Browse Server" button works fine for me.

**Comment by visual74** [comment]
You right. It works fine on my local... Humm I don't know where the permissions miss.. No matter this is my problem ! Thank you very much you can close this issue!
