### ISSUE TITLE
Front-end edit inline

### ISSUE THREAD

**Issue by Edward0625** [joomlaworks/k2-v3-dev-build#186]
Hi!

When i edit an article with inline editor on front-end the CK Editor clean all, ex. div, i, etc. please disable this filter or add a function to put on or off...

THX

**Comment by kavadas** [comment]
K2 is using the Joomla! text filters. You can define what can be posted according to the user group. If this is not working for you, let me know.

**Comment by Edward0625** [comment]
Hello!

I check in global configurations and the super user is setting no filter. I change all user to no filter and i save, but in front end nothing change. 

Before:
![image](https://cloud.githubusercontent.com/assets/7513278/5918084/d7a0af04-a624-11e4-96f2-8046f54388a9.png)

After:
![image](https://cloud.githubusercontent.com/assets/7513278/5918088/e7b19e58-a624-11e4-893f-90585e11ca52.png)

Thank you!
