### ISSUE TITLE
Ordering (Category View)

### ISSUE THREAD

**Issue by kaeau** [joomlaworks/k2-v3-dev-build#187]
I am not sure if the ordering options should already work in the currently build, but nevertheless:
currently it seems that the ordering option in category settings and / or menu item settings have no effect on the frontend display of the regarding category.

**Comment by kavadas** [comment]
Front-end is not complete yet. We need to finalize the parameters. In any case thanks for reporting.

**Comment by kaeau** [comment]
ok, thx for the quick answer!
