### ISSUE TITLE
A number of errors in id and 

### ISSUE THREAD

**Issue by sintos** [joomlaworks/k2-v3-dev-build#188]
Just installed the latest version and when i try to create new items i get a number of errors.
I am not very familiar with coding, so i can't tell you details, but those are the errors i get.

 Warning[2] Illegal string offset 'id'. Line 67 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 67 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Warning[2] Invalid argument supplied for foreach(). Line 46 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: start_date. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: end_date. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: created_by. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _attachments. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _tags. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _media. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _galleries. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 74 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php

**Comment by kavadas** [comment]
Hi,

Is this a fresh installation or an upgrade from K2v2?

**Comment by sintos** [comment]
Its a fresh installation but not on a clean site. Its an installation i did just to try the new K2 on a quickstart installation i did in the "ricochet" template of Rockettheme.

**Comment by sintos** [comment]
If you want i can give access to the site, since its just a demo installation.

**Comment by sintos** [comment]
I reinstalled the quickinstall to be sure if i still get the errors and here is the result i got.

Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: start_date. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: end_date. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: created_by. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _attachments. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _tags. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _media. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: _galleries. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Uknown error type[1024] Undefined property: K2Items: id. Line 101 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php
 Warning[2] Illegal string offset 'id'. Line 74 in file /home/imagehos/public_html/viozois/administrator/components/com_k2/resources/resource.php

**Comment by kavadas** [comment]
Do you have any K2 related extensions installed?

**Comment by sintos** [comment]
No.
Only the ones of rockettheme (like roksprocket) that are K2 compatible.

**Comment by sintos** [comment]
Just tried it in a clean rockettheme template install with joomla 3.4 and here are the results i got in the screenshot
![k2_1](https://cloud.githubusercontent.com/assets/8261466/6378073/6451ff20-bd31-11e4-8c25-6f91a533902f.png)

**Comment by kavadas** [comment]
Did you get a fresh copy of K2v3? I don't think this has to do with the template used.

**Comment by sintos** [comment]
It is a copy of K2V3 downloaded just yesturday...

**Comment by kavadas** [comment]
Unfortunately i cannot verify the issue. Just installed from scratch Joomla! 3.4 and K2v3. I was able to add items and categories. No warnings or notifications.

**Comment by sintos** [comment]
I will set Joomla once again and start installing Rocketthemes templates and components one by one to see if i can reproduce the issue or identify what causes it.

**Comment by sintos** [comment]
I just found out that the problem occurs when i try to install RonNavMenu.
It actually installs RoKExtender plugin and RokNavMenu module.
One of those causes the conflict.
Should i talk to Rockettheme about it ?

**Comment by sintos** [comment]
Actually the issue is caused by RokExtender plugin which is installed together with RokNavMenu.
When i disable the plugin, everything is back to normal.

**Comment by kavadas** [comment]
I took a quick look at the code. RokExtender plugin is triggering some events in the RokNavMenu so the actual issue is raised from the RokNavMenu module. It would be good to let RoketTheme know about the issue. I will also take a look at the code to find a solution.

**Comment by sintos** [comment]
Just heard from Rockettheme that roknavmenu will not be part of the upcoming Gantry5 framework. So it might not even worth it, trying to figure out why this happens.

**Comment by paulvanharen** [comment]
@kavadas 

From the discussion above it appears that this is not a K2 bug. Therefore I propose to close this issue.
