### ISSUE TITLE
Text separator after extrafield

### ISSUE THREAD

**Issue by kewwel** [joomlaworks/k2-v3-dev-build#189]
Its possible  a separator text ( colon, dash ) after each option in the extra field or else the option to display one below the other or side by side ?
![ef](https://cloud.githubusercontent.com/assets/4606218/5938581/8337bac4-a6e3-11e4-8950-771cdc45a114.jpg)

**Comment by kavadas** [comment]
Display of extra fields is something that can be handled in a template override.
