### ISSUE TITLE
K2 v3 Backend Error After the installation and migration

### ISSUE THREAD

**Issue by SimonWayne** [joomlaworks/k2-v3-dev-build#190]
Notice[8] Undefined index: view. Line 429 in file /var/www/vhosts/my-site.com/components/com_k2/helpers/route.php

Notice[8] Undefined index: view. Line 257 in file /var/www/vhosts/my-site.com/components/com_k2/helpers/route.php

**Comment by kavadas** [comment]
Hi,

Which page are you viewing when you get those notices? There always should be a "view" variable in K2 URLs.

**Comment by paulvanharen** [comment]
@kavadas 
I tried to reproduce this issue but I could not. Therefore I propose to close this issue.
