### ISSUE TITLE
Item ordering

### ISSUE THREAD

**Issue by Edward0625** [joomlaworks/k2-v3-dev-build#192]
Hi,

i set the item ordering to "Ordering", but in front end nothing change. I tested with all configurations, but nothing change. In front end the article is ordering "id descending" always.

How to change the order of items in back end? The categories ordering work fine in back end and i set to front end categories ordering "ordering" and it is ok.

So just the aricle ordering not work.

Thank you.

**Comment by kavadas** [comment]
Front-end is incomplete, we are already aware of this. In any case, thank you for reporting.

**Comment by Edward0625** [comment]
Hello,

ok, I'm waiting, but in back-end not work the item ordering. I want to drag an item, but not work.
![image](https://cloud.githubusercontent.com/assets/7513278/6019547/fe928e02-aba1-11e4-8138-246bd9266b56.png)

thank you

**Comment by kavadas** [comment]
It is working for me. Check the browser console for any errors.

**Comment by Edward0625** [comment]
Just one:
GET http://www....media/k2app/vendor/marionette/backbone.marionette.map 404 (Not Found)

**Comment by kavadas** [comment]
This is a warning, we will fix it. However it should not affect the ordering functionality. What's happening when you try to drag the item? Maybe the error is raised after the drag starts.

**Comment by Edward0625** [comment]
Hi,

i check and in the console panel is nothing. When i want to drag an item, the item is moving, but when i want to put the item is moving back. I create a demo categorie with two demo item, and here is work the drag, but when i open my catalog categorie to see the item and moving, the drag not working and is same in demo category. I refresh the page, and the demo categorie work, i open my catalog categorie and not work.

demo work:
![image](https://cloud.githubusercontent.com/assets/7513278/6036786/bfb62cee-ac4a-11e4-9ab8-70471e3b4543.png)

my catalog, the drag not work:
![image](https://cloud.githubusercontent.com/assets/7513278/6036799/f09e07aa-ac4a-11e4-917a-39b69d3bdd14.png)

Thank you!

**Comment by kavadas** [comment]
What's the difference between those categories? Do you have sufficient permissions to edit those categories and items?

**Comment by Edward0625** [comment]
The catalog have sub-category and is deutsch language. I change the language deutsch (demo category) and is work. I create a category and the demo category now is subcategory and not work.

So, if the item is assign subcategory the ordering not work.

Thank you.

**Comment by Edward0625** [comment]
Sorry, i refresh page and demo work, but my catalog no. If you want i create for you and access for my site.

**Comment by Edward0625** [comment]
Hi,
I create a new site with fresh install k2v3. The problem is same, but i change the category ordering, and now the demo is first and my catalog is second and the catalog work and demo category item not work. So, in the first primary category (DEMO) the item drag not work, but in the second primary category (Kabel) work.
![image](https://cloud.githubusercontent.com/assets/7513278/6077218/016a6364-aded-11e4-9ca9-549903ff78d2.png)

**Comment by kavadas** [comment]
I cannot verify the issue. Just tested and everything works fine. Which browser are you using?

**Comment by Edward0625** [comment]
I use Chrome, and now i tested in Firefox and work all. The problem is with the Chrome browser. I clean all in Chrome browser but not work. I think is a conflict with Chrome browser. Have any date plane, when is possible to test in front-end the item ordering? 

Thank you your effort.

**Comment by Edward0625** [comment]
Thank you!!!

**Comment by kavadas** [comment]
You are welcome.
