### ISSUE TITLE
Category column

### ISSUE THREAD

**Issue by Edward0625** [joomlaworks/k2-v3-dev-build#196]
Hi,

the category column in item list is to short. I think if the select, state, featured and language colums were not so wide, you have possibility to make the category column could be wider.
![image](https://cloud.githubusercontent.com/assets/7513278/6086350/23d0370e-ae41-11e4-844e-47da289d93f0.png)

Another possibility is setting the category word limit...

Thank you

**Comment by kavadas** [comment]
Hi,

Category names usually are short.

**Comment by Edward0625** [comment]
Hi,

you are right, but i think if you change the "Author" column to "class=small-1 large-1 columns" and the category column to "class=small-2 large-2 columns" is resolved for me all. An author name is maximum of 3 words, but a cetegory can be more than 3 words.

Thank you!
