### ISSUE TITLE
Disable email in item k2

### ISSUE THREAD

**Issue by kewwel** [joomlaworks/k2-v3-dev-build#198]
In item k2, even for you by setting do not see the email author, it appears.

**Comment by kavadas** [comment]
Hi,

Can you provide more information regarding this? I don't get exactly what you mean.

**Comment by adhouse-ryan** [comment]
The Author email still appears even when disabled in the general settings.

**Comment by kavadas** [comment]
@kewwel Front-end code is not finalized yet. However i just made several tests regarding the author email in the item view and it works fine for me. 

@adhouse-ryan Are you also talking about the item view?

**Comment by kewwel** [comment]
I noticed that it disappears only by setting in the category.
If so, you must have an option to enable, disable, in general settings?
I saw that some things can only be unset by category. Would not it be better to set all the general settings and have overrides by setting the category?

**Comment by kewwel** [comment]
With me, appears in item view.

**Comment by paulvanharen** [comment]
@kavadas 
This option now works fine with me. I expect that this was fixed in the september 2015 update of the front-end. I propose to close this issue.
