### ISSUE TITLE
Conflict Js Adsense and item k2 with url rewrtting

### ISSUE THREAD

**Issue by kewwel** [joomlaworks/k2-v3-dev-build#199]
I noticed that the adsense code does not appear in item k2, when the mode url rewriting is enabled. However it appears in the category k2. I made a video testing this.:
http://screencast-o-matic.com/watch/con1YJegaa

**Comment by kewwel** [comment]
Enabling / disabling url rewritting, adding suffix or not, the adsense code works and does not work in the category page and the item page. Never both at the same time. In Chrome browser does not appear in any of the two.

**Comment by kavadas** [comment]
Modules in Joomla! are displayed based on menu links. If you are viewing a page which is not assigned to a menu link then it's normal that the module is not displayed.

**Comment by kewwel** [comment]
Kavadas, in the video is visible to see the html module containing the adsense code, is set to all pages. I will leave to do more tests in the stable version.
Is there any release date for her?

**Comment by heyjoecampbell** [comment]
Hi @kewwel have you tried using NoNumber Sourcerer for adding code into K2 (via the content editor or extra fields)? 

Here's the link:
https://www.nonumber.nl/extensions/sourcerer
