### ISSUE TITLE
Language strings not loaded in Joomla 3.4 

### ISSUE THREAD

**Issue by kairoen** [joomlaworks/k2-v3-dev-build#201]
Upgraded my Joomla 3.3.6 site to 3.4 beta 2, and noticed that strings in K2 are no longer loaded.
![k2](https://cloud.githubusercontent.com/assets/1314972/6127339/0820cf6e-b12a-11e4-8de6-ca7c8e86a2f5.jpg)

I am not sure if this is a bug in 3.4 beta 2 or some changes in the core of Joomla 3.4 release.

**Comment by kavadas** [comment]
Does the file administrator/language/en-GB/en-GB.com_k2.ini exists on your server?

**Comment by kairoen** [comment]
yes. I have also upgraded the site to 3.4 beta 3, same issue.

**Comment by kavadas** [comment]
Just installed Joomla! 3.4 beta 3 and K2 v3 and everything works fine for me. Are there any other extensions installed?

**Comment by kavadas** [comment]
Do you face this issue in front-end or in back-end?

**Comment by kairoen** [comment]
I only see this in backend. I can not see the frontend, because the K2 item won't load. It shows just a blank page. In Apache error log I get this when accessing the item in frontpage:

[Wed Feb 11 22:10:57.767349 2015] [:error] [pid 2154] [client xx.xxx.xx.198:57628] FastCGI: server "/var/www/ccccc/cgi-bin/php5-fcgi-*-80-xxxx.no" stderr: PHP message: PHP Fatal error:  Access level to K2Router::$menu must be public (as in class JComponentRouterBase) in /var/www/xxxx/components/com_k2/router.php on line 880, referer: http://www.xxxx.no/administrator/index.php?option=com_menus&view=items

**Comment by kairoen** [comment]
Stupid me ... I have set the language to Norwegian in backend - there are no language files for Norwegian.

**Comment by kavadas** [comment]
Thanks for reporting both issues.

**Comment by LunaBawa** [comment]
Am installing k2 for the first time on my site running on joomla 3.4 and it just wont install...please any idea of any fix to this bug?

**Comment by kavadas** [comment]
@LunaBawa 

You are asking for help on a closed issue. You are also asking for help for something that is completely irrelevant with this issue. 

If you are completely sure that this is an issue of the extension and not a server issue ( filesystem permissions, can you install other extensions ? ) then create a new issue providing all the details.
