### ISSUE TITLE
REQUEST: Allow frontend editing of Category Description

### ISSUE THREAD

**Issue by williamconifer** [joomlaworks/k2-v3-dev-build#202]
I are getting requests from some of my clients to allow for front-end editing of a K2 category description. I know this is not possible in the current 2.6.x version of K2. Thus we are asking that this be added to a future version.

This is especially important for large, content heavy websites where we use a category description as a "summary or intro" for a category branch of content.

**Comment by kavadas** [comment]
Hi,

All the editing capabilities that are available in back-end are also available in front-end in k2v3. So, what you are asking for is already there. Have you tested K2v3?

**Comment by williamconifer** [comment]
Thanks Kavadas. This is great news. I haven't had a chance to test V3 but now I'm more motivated.

Keep up the good work!

**Comment by kavadas** [comment]
You are welcome.
