### ISSUE TITLE
Item edit date in persian calender

### ISSUE THREAD

**Issue by afarineshweb** [joomlaworks/k2-v3-dev-build#204]
this bug was in previews version too.
when we edit an item , k2 create date destroy.
our team solve the problem that for ourselves, we hope this bug will solve for default in this version
if you pleased we can bring the solution for you.

**Comment by kavadas** [comment]
Hi,

Can you please provide more details on this? Which is the language file that you are using? Where does exactly the issue occurs? I would be happy to see how you solved the issue.

**Comment by afarineshweb** [comment]
hi,
the language we use is persian.
when language in back-end is english there is no problem.
but when we turn to persian the calender in item section get wrong.
if you want to see this error, change the joomla admin language to persian and go to k2 > items.
then create an item, if you see "Created" col, date is ok but not the hour and minute.this is the first problem.
![1](https://cloud.githubusercontent.com/assets/6479243/6344160/fe706ba6-bc09-11e4-81a7-c10e54f392ab.png)

after this get back and "edit" the item that created before, "save and close" after edting.
now see the  "Created" col  again the date and time get destroy.
![2](https://cloud.githubusercontent.com/assets/6479243/6344202/9bbe9c3e-bc0a-11e4-9c75-9f3c696389be.png)

**Comment by kavadas** [comment]
I applied this https://github.com/joomlaworks/k2-v3-dev-build/commit/92d4653cc49935320ac5dd4b53e96bcad59639f8 which should fix the issue when editing the item. However, i don't get what's wrong with the time in the first screenshot. Is it the timezone or the format?

**Comment by afarineshweb** [comment]
thank you,the editing problem solved.
yeah you are right first problem, the time because of the joomla time zone didnt set to my time zone.

**Comment by kavadas** [comment]
So is everything working fine now? Should i close the issue?

**Comment by afarineshweb** [comment]
yes, thanks a lot.
it works great

there is a another problem about calender that is "k2 tools calender" problem.
that is this module just show AD months, is it need to follow it here or create another issue.

**Comment by kavadas** [comment]
It would be better to create a different issue. I will close this issue now. Thank you for your feedback.
