### ISSUE TITLE
More in this category

### ISSUE THREAD

**Issue by Edward0625** [joomlaworks/k2-v3-dev-build#210]
Hi,

the items is not appear in ordering in "More in this category"! I know the front-end is not ready! I tested K2 V3 complex and you make me very happy if you make the item ordering function work from front-end. Now i setting in back-end to see items in ordering, but now this function not work.

Thank you

**Comment by kavadas** [comment]
Hi,

Just tested and the ordering is correct in the items navigation. What's exactly the issue?

**Comment by Edward0625** [comment]
Hi,

sorry i closed, so

in back-end i setting the items ordering to see in front-end "ordering".
![image](https://cloud.githubusercontent.com/assets/7513278/6390830/fe4ad394-bdaf-11e4-8448-2c5a33852fce.png)

**Comment by Edward0625** [comment]
The items ordering in back-end in a category for example:
![image](https://cloud.githubusercontent.com/assets/7513278/6390914/15afbddc-bdb1-11e4-8fa1-28107ea66434.png)

**Comment by Edward0625** [comment]
In front-end the items not appear how i setting in back-end:
![image](https://cloud.githubusercontent.com/assets/7513278/6390950/4241edfc-bdb1-11e4-9a9a-ad37c2c0436f.png)

I tested with all setting but in front-end the items ordering not change.

Thank you

**Comment by Edward0625** [comment]
And i go to see first item (H07BQ-F) and in more items in this category appear an another items in this category, not the next (H05BQ-F:
![image](https://cloud.githubusercontent.com/assets/7513278/6391042/056a8bd6-bdb2-11e4-89e5-2123076930a2.png)

Thank you!
