### ISSUE TITLE
 K2_DUPLICATE_ALIAS 

### ISSUE THREAD

**Issue by PLFoxNET** [joomlaworks/k2-v3-dev-build#213]
Hello,

When creating a sub-category in the sub-category when in another sub-category there is already such an alliance, the error "K2_DUPLICATE_ALIAS".

For example:

Wiki (alliance: wiki)
| -Games (alliance: games)

news (alliance: news)
| -Games (alliance: games)

I'm thinking that in this case the arrangement of sub-categories (games) there is no duplication of the alliance as a whole ....

**Comment by kavadas** [comment]
Hi,
The category and item alias should be unique.

**Comment by PLFoxNET** [comment]
Okay, but in my opinion, unique within the category in which it is located

**Comment by kavadas** [comment]
Thank you for sharing your opinion but we are not going to change this.

**Comment by PLFoxNET** [comment]
Ok, but then I see a conflict between the version 2.X and 3.X version

The K2 v2.x could create the same alliances in different sub categories

The problem appears when updating K2 version 2.x to version 3.x

**Comment by kavadas** [comment]
Have you tried this or this is just a thought? The update process takes care of this.

**Comment by PLFoxNET** [comment]
On the version before the week when upgrading 2.x to 3.x K2 was empty database was not broadcast, I thought it was a bug (3.x may not yet be captured update). I'll do myself again to test the update and see what will be its effect. In any event, I have in terms of a lot of duplicates.

I have 2 main categories (wiki and news) and the same subcategories (names and alliances) for each of the major categories.

Tomorrow I'll know how the test went off.

**Comment by PLFoxNET** [comment]
In Joomla 3.4 you can create the same alliances, such a condition is only to be unique at that level.

Please find attached some screenshots.

If you now have to act as alliances that are unique in the whole, and not only in the parent category, it misses the goal - SEO. Unimaginable yourself a note in the alliance of "54f5f5fe707d1" to him. You may not still to drive to understand. My English is not too good, and maybe something wrong is trying to convey.

Please see the screenshots and possibly allow others to comment on that use K2 on this point.

For the current version of the K2 v3 has been running a data update, but there are warnings, also on the screenshot.

![joomla-v3 4-cat](https://cloud.githubusercontent.com/assets/2227327/6484159/a9c80bce-c279-11e4-847f-6d6351767b50.jpg)
![k2-v2 6 9-cat](https://cloud.githubusercontent.com/assets/2227327/6484160/a9c8331a-c279-11e4-8d5c-c20540660693.jpg)
![k2-v2 6 9-to-v3 0 0-dev](https://cloud.githubusercontent.com/assets/2227327/6484161/a9ca65d6-c279-11e4-8d1b-2bb0dbe7b944.jpg)
![k2-v3-cat-news-gta-i](https://cloud.githubusercontent.com/assets/2227327/6484163/a9cee9e4-c279-11e4-870f-d29189b1547e.jpg)
![k2-v3-cat-wiki-gta-i](https://cloud.githubusercontent.com/assets/2227327/6484162/a9cbbb8e-c279-11e4-8c02-d25fda3b14b1.jpg)
