### ISSUE TITLE
Do not see the files of language

### ISSUE THREAD

**Issue by PLFoxNET** [joomlaworks/k2-v3-dev-build#214]
Hello,

From the administrator if the language is other than English are displayed constant names instead of their linguistic value.

For example: K2_PARENT, K2_ACCESS

When I change the language from the administrator is English are displayed values.

In the attached screenshots.
![schowek01-k2-other](https://cloud.githubusercontent.com/assets/2227327/6484430/210f72a6-c27c-11e4-8a78-12102cdc09ec.jpg)
![schowek01-k2-en](https://cloud.githubusercontent.com/assets/2227327/6484431/2138b2c4-c27c-11e4-87da-b09dd581d005.jpg)

**Comment by kavadas** [comment]
Have you installed the relevant K2 language pack? Note that this is not a stable version so, some strings might be missing.
