### ISSUE TITLE
Upgrade from k2 v2.6.9 fails and deletes all categories and items

### ISSUE THREAD

**Issue by Simon-Davies** [joomlaworks/k2-v3-dev-build#227]
When installing over k2 v2.6.9 the upgrade fails and deletes all categories and items

**Comment by kavadas** [comment]
Hi,

The upgrade does not delete any data. It is just renaming the database tables. When the upgrade fails it will show a message and it will try to restore the previous K2 version and the data. Did you get that message? What was the exact output?

**Comment by Simon-Davies** [comment]
Why does it rename all of the tables? It means all content on the site can't be seen :/

**Comment by Simon-Davies** [comment]
The update completes but throws errors and then all content can't be been due to the renaming of the tables. I can't remember the exact errors but I can't test the beta again if everything on my website just disappears

**Comment by kavadas** [comment]
The tables are renamed so we can roll back to the previous version when the update fails. I am afraid that without the specific errors i cannot troubleshoot this.

**Comment by Simon-Davies** [comment]
I have fixed the issue and data migration was succesful :) I'm sorry the issue was on my end. Working as a penetration tester I never give up until a probelm is solved lol.I'm assuming the data migrator is a .php file? If anyone else is having problems with the data migrator tell them to comment out the code below if it exists in their .htaccess file:

## Disallow access to rogue PHP files throughout the site, unless they are explicitly allowed
##RewriteCond %{REQUEST_FILENAME} (\.php)$
##RewriteCond %{REQUEST_FILENAME} !(/index[23]?\.php)$
##RewriteCond %{REQUEST_FILENAME} -f
##RewriteRule (.*\.php)$ - [F]
