### ISSUE TITLE
Hide Un-Used Module Parameters

### ISSUE THREAD

**Issue by heyjoecampbell** [joomlaworks/k2-v3-dev-build#230]
Reduce clutter of showing all parameters, instead only show the selected parameters for K2 Tools (Select module functionality) and K2 Content Module (Source).

**Comment by kavadas** [comment]
It should already work like that. Just tested and it works like that for me.

**Comment by heyjoecampbell** [comment]
Are you referring to the v3 build correct? I was basing my comment on 2.6.8

You guys should create a K2 v3 Playground so people can test drive it and provide feedback

**Comment by kavadas** [comment]
Yes, i was talking about K2v3 since you opened the issue in K2v3 repository. You can download the package from this repository and test it.
