### ISSUE TITLE
Error install script.k2.php on line 65

### ISSUE THREAD

**Issue by bugsmafia** [joomlaworks/k2-v3-dev-build#235]
Fatal error: Only variables can be passed by reference in /home/y/yii72/siteebel/public_html/tmp/install_55c9d53ec0f6b/k2-v3-dev-build-master/script.k2.php on line 65

PHP Version	5.4.42
Web Server	Apache/2.2.29
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.0-dev Development [ Ember ] 2-July-2015 16:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by kricore** [comment]
The latest commit solves this issue.
Thank you for your feedback.
