### ISSUE TITLE
Uncaught TypeError when using mod_k2_content on a non com_k2 page

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#238]
If you create a mod_k2_content module on a page where com_k2 is not present, you get the following console error:

```
Uncaught TypeError: jQuery(...).magnificPopup is not a function
```

It's because the jquery.magnific-popup.min.js library is not called in the head when using mod_k2_content alone. 

That alone is fine, as you typically don't need modals for your K2 Content modules. But k2.js is loaded on all pages, even if K2 or its modules are not in use. Line 22 of k2.js should either be scoped in such a way to prevent errors if magnific popup isn't loaded, or ensure it's always loaded alongside k2.js.

**Comment by kavadas** [comment]
Thank you for reporting this.

**Comment by kbrookes** [comment]
A pleasure mate. Glad to contribute back.
