### ISSUE TITLE
Several editors not working with K2 v3

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#246]
I've been trialling several different editors with K2 v3 and have found that quite a few that work perfectly with com_content are either buggy or fail to load entirely with K2 v3.

1) JCE Editor and Tiny MCE work perfectly

2) DropEditor doesn't load at all: https://www.joomunited.com/products/dropeditor
Console: Uncaught TypeError: Cannot read property 'getEditor' of undefined

3) YeeEditor doesn't load at all: http://yeedeen.com/extensions/yeeditor
No console errors

4) Redactor JS causes the entire K2 backend to crash: http://stackideas.com/downloads/plugins

Pretty much anything that isn't TinyMCE based doesn't work. I've only included editors that both worked perfectly in com_content and that I consider to be a solid editor.

BTW - the ajaxified backend item list now means that users need to refresh the browser window, not just close and reopen items for changes to the editor to be applied.

**Comment by kavadas** [comment]
See #52
