### ISSUE TITLE
Tag autocomplete fails if there's a space in the tag

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#247]
I'm dealing with some longish tags for a client and while it's perfectly possible to have tags with spaces and special characters (which is awesome, BTW), when selecting a tag in the admin item editor the autocomplete fails to continue offering suggestions once you get to the space.

If my clients have as tags:

brand recognition
brand names
brand images

If I type 'brand', then I see the full list of suggestions, but if I type 'brand ', then the suggestions disappear.

In the specific example I'm working on, I might have 20 or 30 tags starting with 'brand', so scrolling or keyboarding through the list is impractical compared to autocomplete.

**Comment by kavadas** [comment]
Thanks for reporting.
