### ISSUE TITLE
Child categories don't have sef link

### ISSUE THREAD

**Issue by chivitli** [joomlaworks/k2-v3-dev-build#249]
Create a category and a child category. Create menu link to the parent category only. Child category will get the link like /_component/k2/itemlist/category/3-child-category_ instead of _/parent-category/itemlist/category/3-child-category_

**Comment by kavadas** [comment]
This is the intended behavior. Categories are not inheriting the parent's menu links.

**Comment by chivitli** [comment]
That's a change in links compared to version 2, even when legacy advanced sef mode is enabled

**Comment by kavadas** [comment]
That's not true. In the previous version there was also no relation between parent and child categories in terms of menu links. What was happening actually was that if no matched menu link was found the menu link of the current page ( even if it was not the parent category ) was inherited. This caused many issues including duplicate URLs for the same page etc.

**Comment by chivitli** [comment]
That's exacy the change I mean :) But again, fine with me as long as that's the behaviour on which can be counted
