### ISSUE TITLE
Filtering by category in admin item list, filtered selection isn't persisted

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#250]
When a backend user filters by category in the item list, if an item is edited when 'save and close' is chosen the item list the user is returned to is no longer filtered by category.

**Comment by kavadas** [comment]
I cannot verify the issue. Just tested and the filter remains after saving the item.

**Comment by kbrookes** [comment]
Weird - this was bugging me senseless yesterday but seems to be behaving itself today.

**Comment by kbrookes** [comment]
This one is back - I've had two days of constant editing where I've needed to reset the category selection after every save.

**Comment by kavadas** [comment]
I need more information on this. I still cannot reproduce the issue. Do the rest options work? Page number for example?

**Comment by kbrookes** [comment]
Yes, everything else works - sorting, for example, works perfectly, as does pagination.

And suddenly this has been working again. I can't rule out that it's a browser memory issue on my end, so I'm just going to close this unless I can get something more concrete.

**Comment by kavadas** [comment]
What's the browser you are using? Maybe it's indeed a browser caching issue.
