### ISSUE TITLE
Frontend: Date format

### ISSUE THREAD

**Issue by Twincarb** [joomlaworks/k2-v3-dev-build#254]
The date format on the front end is showing as:

%AM, %26 %378 %2015 %09:%Aug

Guess your aware of this already as the frontend isn't finished yet

**Comment by kavadas** [comment]
Hi,

Are you using a language other than English?

**Comment by Twincarb** [comment]
No is default English
Site was upgraded from 2.6.9 
When a new item is created it also has the same issue. I will have a look later to see if the same occurs on the modified date time format as well
