### ISSUE TITLE
Groups of extra fields at various template positions.

### ISSUE THREAD

**Issue by kewwel** [joomlaworks/k2-v3-dev-build#256]
Is there some code I can show groups of extra fields in different places on the item page. As k2 allows you many things, just miss this trick to equalize the components of real estate, cars and other types of directories.
Example: Group 1 at the top of the page item and group 2,3,4 and so on elsewhere.

I remember it was possible to display the result of an extra field, via code.

![extrafield](https://cloud.githubusercontent.com/assets/4606218/10083204/c33a5d82-62d3-11e5-8f14-c9e5a7a345f6.jpg)

**Comment by kavadas** [comment]
You can render an extra field based on it's alias. You can read more regarding this at http://getk2.org/blog/1068-k2-v262-now-available .

**Comment by kewwel** [comment]
Thank U for information.
