### ISSUE TITLE
sh404SEF doesn't respect new advanced SEF settings

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#261]
I've just been testing sh404SEF with K2 v3 and found that neither the new standard or legacy SEF settings around categories are respected.

The behaviour seems to be that it completely strips the category (alias in this case) from the URL when viewing the item.

With just K2 and Joomla SEF it behaves as expected when I have the /category-alias/item-alias pattern set in K2 settings.

I reached out to Weeblr first and they mentioned that I should raise it here.

**Comment by kavadas** [comment]
You cannot combine both of them. K2 advanced SEF is to be used when no SEF extensions are used. Since you are using a SEF extension you need to turn of K2 advanced SEF.

**Comment by kbrookes** [comment]
Ah - I can see that now in 2.6.9. But previously there's been an option for mapping aliases of categories to sh404SEF and handling of itemIDs. Will that be making a return?

**Comment by kavadas** [comment]
I will create a new issue for the missing SH404SEF integration. Thank you again for reporting.
