### ISSUE TITLE
Tags editor accepts tags that item tag selection doesn't allow

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2-v3-dev-build#262]
The build I'm doing at the moment, the client has a wacky sense of what constitutes a tag and have tags like:

Employee branding / employee value proposition (EVP)

and 

Brand logo, identity & design

Oddly, the first one with a slash works as a tag. The second is accepted when creating a tag in the tag section and appears in the tag drop-down when editing an item's tag.

However, on saving the item the tag is split at the comma.

It'd be good to harmonise both the tag editor and the tag selector in the item. (preferably where commas can be accepted as part of the tag).

**Comment by kavadas** [comment]
You are right about this. But in order to fix this we will have to sacrifice the comma functionality of the widget ( now pressing comma will add a tag )  .

**Comment by kbrookes** [comment]
Fair enough, I suspected that would be the case.

It's more important to have it consistent across both - whichever way is most usable should win.

**Comment by kavadas** [comment]
I agree with you. 

@fevangelou What's your opinion on this?

**Comment by fevangelou** [comment]
Agree with Lefteris on this one.
