### ISSUE TITLE
Unable to upgrade from K2 2.6.9 to K2 3.0

### ISSUE THREAD

**Issue by Simon-Davies** [joomlaworks/k2-v3-dev-build#266]
Warning

Unknown column 'asset_id' in 'field list' SQL=INSERT INTO j40jm_k2_categories (id, asset_id, parent_id, lft, rgt, path, level, title, alias, state, access, description, image, extra_fields, template, inheritance, created, created_by, created_by_alias, modified, modified_by, checked_out, checked_out_time, metadata, plugins, params, language) VALUES (1, 0, 0, 0, 1, '', 0, 'ROOT', 'root', 0, 1, '', '', '', '', 0, '0000-00-00 00:00:00', 0, '', '0000-00-00 00:00:00', 0, 0, '0000-00-00 00:00:00', '', '', '', '');
Error

Error installing component

**Comment by paulvanharen** [comment]
@kavadas 
I tried to reproduce this issue. I could not find the reported issue. Therefore I recommend closing this report.
