### ISSUE TITLE
Imported Items do not have the correct Created date on the frontend website

### ISSUE THREAD

**Issue by Simon-Davies** [joomlaworks/k2-v3-dev-build#270]
After importing items from k2 2.6.9 Items do not have the correct Created date on the frontend website. The date is not even an actual date it has % symbols and looks like URL encoding.

**Comment by kavadas** [comment]
This has probably to do with your template overrides or your language files. The date is imported in the database correctly. Can you look at your language files?

**Comment by Simon-Davies** [comment]
I use the English language file. What do I need to do with the language files?

**Comment by Twincarb** [comment]
Simon, 
I think what your describing is the same as the issue here which I submitted some weeks back.
https://github.com/joomlaworks/k2-v3-dev-build/issues/254

**Comment by kavadas** [comment]
See #254
